name: "publish"

on:
  push:
    branches:
      - master

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: "--target x86_64-unknown-linux-gnu"
          - platform: "ubuntu-22.04-arm"
            args: "--target aarch64-unknown-linux-gnu"
          - platform: "windows-latest"
            args: "--target x86_64-pc-windows-msvc"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin --debug"
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin --debug"
          - platform: "ubuntu-22.04"
            args: "--target x86_64-unknown-linux-gnu --debug"
          - platform: "ubuntu-22.04-arm"
            args: "--target aarch64-unknown-linux-gnu --debug"
          - platform: "windows-latest"
            args: "--target x86_64-pc-windows-msvc --debug"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.5

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.1

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: contains(matrix.platform, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils

      - name: install frontend dependencies
        run: bun install

      - uses: tauri-apps/tauri-action@f31fac17d09882736b3aee2fa01630731e631aad
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: room237-v__VERSION__
          releaseName: "Room 237 v__VERSION__"
          updaterJsonPreferNsis: true
          releaseDraft: true
          prerelease: false
          releaseAssetNamePattern: "room237-[mode]-[platform]-[arch][setup][ext]"
          uploadPlainBinary: true
          args: ${{ matrix.args }}
